[supervisord]
nodaemon=true
user=root
loglevel=debug

[program:health_check]
command=/usr/local/bin/python /app/glam_api/cluster_health.py
directory=/app  ; Your Django project directory
autostart=true
autorestart=true
port=8000

[program:djangoq]
command=/usr/local/bin/python /app/glam_api/manage.py qcluster  ; Your Django Q worker command
directory=/app
autostart=true
autorestart=true
port=8001
