# Generated by Django 3.2.15 on 2022-10-12 17:55

import config.storage_backends
import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Dataset name. Generated automatically from file name.', max_length=256)),
                ('slug', models.SlugField(blank=True, help_text='Slug for dataset. (automatically generated)', max_length=256, unique=True)),
                ('admin_units', models.JSONField(blank=True, help_text='List of administrative units present in the administrative layer dataset.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra dataset details.', null=True)),
                ('date_created', models.DateField(help_text='Date the crop mask dataset version was created.')),
                ('date_added', models.DateField(auto_now_add=True, help_text='Date dataset added to system.')),
                ('local_path', models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', path='/data/glam2/api/glam_api/local_files/adminlayers', recursive=True)),
                ('file_object', models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage_backends.RasterStorage(), upload_to='regions')),
            ],
            options={
                'verbose_name': 'administrative layer dataset',
            },
        ),
        migrations.CreateModel(
            name='AdminLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Administrative layer name.', max_length=256)),
                ('adminlayer_id', models.SlugField(blank=True, help_text='A unique character ID to identify Administrative Layer records.', max_length=256, unique=True)),
                ('display_name', models.CharField(help_text='Administrative Layer display name.', max_length=256)),
                ('desc', models.TextField(help_text='Brief description of Adminsitrative Layer.')),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra details.', null=True)),
                ('admin_units', models.JSONField(blank=True, help_text='List of administrative units present in the administrative layer.', null=True)),
                ('date_created', models.DateField(help_text='Date the Administrative Layer version was created.')),
                ('date_added', models.DateField(help_text='Date the Administrative Layer was added to the system.')),
                ('primary_raster', models.FileField(blank=True, help_text='Original Administrative Layer raster file. (if available)', null=True, storage=config.storage_backends.RasterStorage(), upload_to='regions')),
                ('vector_file', models.FileField(blank=True, help_text='Original Administrative Layer vector file. (if available)', null=True, storage=config.storage_backends.VectorStorage(), upload_to='vectors')),
            ],
            options={
                'verbose_name': 'administrative layer',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of crop.', max_length=256)),
                ('crop_id', models.SlugField(blank=True, help_text='A unique character ID to identify Crop records.', max_length=256, unique=True)),
                ('display_name', models.CharField(help_text='Crop display name.', max_length=256)),
                ('desc', models.TextField(help_text='Description of crop.')),
            ],
        ),
        migrations.CreateModel(
            name='CropMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cropmask name.', max_length=256)),
                ('cropmask_id', models.SlugField(blank=True, help_text='A unique character ID to identify Crop Mask records.', max_length=256, unique=True)),
                ('display_name', models.CharField(help_text='Cropmask display name.', max_length=256)),
                ('desc', models.TextField(help_text='Brief cropmask decription.')),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra details.', null=True)),
                ('date_created', models.DateField(help_text='Date that the cropmask version was created.')),
                ('date_added', models.DateField(help_text='Date cropmask added to the system.')),
                ('raster_file', models.FileField(blank=True, help_text='Original cropmask raster file. (if available)', null=True, storage=config.storage_backends.RasterStorage(), upload_to='masks')),
                ('vector_file', models.FileField(blank=True, help_text='Original cropmask vector file. (if available)', null=True, storage=config.storage_backends.VectorStorage(), upload_to='vectors')),
                ('crop_type', models.ForeignKey(help_text='Crop that the mask represents.', on_delete=django.db.models.deletion.PROTECT, to='glam.crop')),
            ],
            options={
                'verbose_name': 'crop mask',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Source name.', max_length=256)),
                ('source_id', models.SlugField(blank=True, help_text='A unique character ID to identify Data Source records.', max_length=256, unique=True)),
                ('display_name', models.CharField(help_text='Source display name.', max_length=256)),
                ('desc', models.TextField(help_text='Brief source description.')),
                ('link', models.URLField(help_text='URL link to Source.')),
                ('logo', models.ImageField(blank=True, help_text='Source logo.', null=True, storage=config.storage_backends.PublicStorage(), upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique id for export', primary_key=True, serialize=False)),
                ('started', models.DateTimeField(auto_now_add=True, help_text='Date/Time export started.')),
                ('completed', models.DateTimeField(blank=True, help_text='Date/Time export completed.', null=True)),
                ('file_object', models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage_backends.RasterStorage(), upload_to='exports')),
            ],
            options={
                'verbose_name': 'image export',
            },
        ),
        migrations.CreateModel(
            name='MaskDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Dataset name. Generated automatically from file name.', max_length=256)),
                ('slug', models.SlugField(blank=True, help_text='Slug for dataset. (automatically generated)', max_length=256, unique=True)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra dataset details.', null=True)),
                ('date_created', models.DateField(help_text='Date the crop mask dataset version was created.')),
                ('date_added', models.DateField(auto_now_add=True, help_text='Date dataset added to system.')),
                ('local_path', models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', path='/data/glam2/api/glam_api/local_files/cropmasks', recursive=True)),
                ('file_object', models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage_backends.RasterStorage(), upload_to='masks')),
                ('crop_mask', models.ForeignKey(help_text='CropMask that the crop mask dataset belongs to.', on_delete=django.db.models.deletion.CASCADE, to='glam.cropmask')),
            ],
            options={
                'verbose_name': 'crop mask dataset',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name.', max_length=256)),
                ('product_id', models.SlugField(blank=True, help_text='A unique character ID to identify Product records.', max_length=256, unique=True)),
                ('display_name', models.CharField(help_text='Product display name.', max_length=256)),
                ('desc', models.TextField(help_text='Description of product.')),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra details.', null=True)),
                ('link', models.URLField(blank=True, help_text='URL to product source or additional details.', null=True)),
                ('date_start', models.DateField(help_text='Date the product was first made available.')),
                ('date_added', models.DateField(help_text='Date the product was added to the system.')),
                ('composite', models.BooleanField(help_text='Is the product a composite?')),
                ('composite_period', models.IntegerField(blank=True, help_text='If the product is a composite - the compositing period. (in days)', null=True)),
                ('source', models.ForeignKey(help_text='Product data source/organization.', on_delete=django.db.models.deletion.PROTECT, to='glam.datasource')),
            ],
            options={
                'verbose_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelim', models.BooleanField(default=False, help_text='Is this dataset preliminary/near real time?')),
                ('name', models.CharField(blank=True, help_text='Dataset name. Generated automatically from file name.', max_length=256)),
                ('slug', models.SlugField(blank=True, help_text='Slug for dataset. (automatically generated)', max_length=256, unique=True)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra dataset details.', null=True)),
                ('date', models.DateField(blank=True, db_index=True, help_text='Dataset date. If product is a composite see product details for when the date falls in the compositing period. Derived automatically from file name.')),
                ('date_added', models.DateField(auto_now_add=True, help_text='Date dataset added to system.')),
                ('local_path', models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', path='/data/glam2/api/glam_api/local_files/products', recursive=True)),
                ('file_object', models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage_backends.RasterStorage(), upload_to='rasters')),
                ('product', models.ForeignKey(help_text='Product the dataset belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='glam.product')),
            ],
            options={
                'verbose_name': 'product dataset',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ZonalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unit_id', models.IntegerField(db_index=True, help_text='Administrative Unit of ZonalStats.')),
                ('arable_pixels', models.FloatField(help_text='Number of pixels representing arable land within the specified administrative unit.')),
                ('percent_arable', models.FloatField(help_text='Percent of arable pixels for the product and mask dataset comination.')),
                ('mean_value', models.FloatField(help_text='Mean calculated for specified administrative unit using the product and mask dataset combination.')),
                ('date', models.DateField(db_index=True, help_text='Date the ZonalStats represent, derived from the product dataset')),
                ('admin_dataset', models.ForeignKey(help_text='Administrative Layer dataset of ZonalStats.', on_delete=django.db.models.deletion.CASCADE, to='glam.admindataset')),
                ('mask_dataset', models.ForeignKey(help_text='Cropmask dataset of ZonalStats.', null=True, on_delete=django.db.models.deletion.CASCADE, to='glam.maskdataset')),
                ('product_dataset', models.ForeignKey(help_text='Product dataset of ZonalStats.', on_delete=django.db.models.deletion.CASCADE, to='glam.productdataset')),
            ],
            options={
                'verbose_name': 'zonal stats',
                'verbose_name_plural': 'zonal stats',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variable name.', max_length=256)),
                ('variable_id', models.SlugField(blank=True, help_text='A unique character ID to identify Variable records.', max_length=256, unique=True)),
                ('display_name', models.CharField(help_text='Variable display name.', max_length=256)),
                ('desc', models.TextField(help_text='Description of variable measured by product.')),
                ('scale', models.FloatField(help_text='Scale to apply to measurements of variable derrived from product.')),
                ('units', models.CharField(help_text='Units of measurement for variable.', max_length=64)),
                ('unit_abbr', models.CharField(blank=True, help_text='Abbreviation of units of measurement.', max_length=32, null=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='variable',
            field=models.ForeignKey(help_text='Variable measured by product.', on_delete=django.db.models.deletion.PROTECT, to='glam.variable'),
        ),
        migrations.AddField(
            model_name='maskdataset',
            name='product',
            field=models.ForeignKey(help_text='Product that the crop mask dataset belongs to.Necessary for matching product resolution in ZonalStats calculation.', on_delete=django.db.models.deletion.CASCADE, related_name='mask_datasets', to='glam.product'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag'),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='source',
            field=models.ForeignKey(help_text='Cropmask source.', on_delete=django.db.models.deletion.PROTECT, to='glam.datasource'),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag'),
        ),
        migrations.AddField(
            model_name='crop',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag'),
        ),
        migrations.CreateModel(
            name='Colormap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Colormap name.', max_length=256)),
                ('colormap_id', models.SlugField(blank=True, help_text='A unique character ID to identify Colormap records.', max_length=256, unique=True)),
                ('desc', models.TextField(blank=True, help_text='Description of product.', null=True)),
                ('colormap_type', models.CharField(choices=[('perceptually-uniform-sequential', 'Perceptually Uniform Sequential'), ('sequential', 'Sequential'), ('sequential-2', 'Sequential (2)'), ('diverging', 'Diverging'), ('cyclic', 'Cyclic'), ('qualitative', 'Qualitative'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', help_text='Category/Type of colormap. (sequential, diverging, qualitative, etc.)', max_length=64)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('file_object', models.FileField(blank=True, help_text='Colormap file. (.npy)', storage=config.storage_backends.ColormapStorage(), upload_to='colormaps')),
                ('tags', models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyBaselineDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Dataset name. Generated automatically from file name.', max_length=256)),
                ('slug', models.SlugField(blank=True, help_text='Slug for dataset. (automatically generated)', max_length=256, unique=True)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata field to provide extra dataset details.', null=True)),
                ('day_of_year', models.IntegerField(blank=True, help_text='Day of year that the baseline represents.Automatically derived from file name.')),
                ('baseline_length', models.CharField(blank=True, choices=[('5year', 'Five Year'), ('10year', 'Ten Year'), ('full', 'Full')], help_text='Length of Baseline', max_length=16)),
                ('baseline_type', models.CharField(blank=True, choices=[('mean', 'Mean'), ('median', 'Median')], help_text='Type of Baseline calculation.', max_length=16)),
                ('date_added', models.DateField(auto_now_add=True, help_text='Date dataset added to system.')),
                ('date_updated', models.DateField(blank=True, help_text='Date Baseline dataset updated/added to.')),
                ('local_path', models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=200, path='/data/glam2/api/glam_api/local_files/baselines', recursive=True)),
                ('file_object', models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage_backends.RasterStorage(), upload_to='rasters')),
                ('product', models.ForeignKey(help_text='Product that the dataset is a Baseline of.', on_delete=django.db.models.deletion.CASCADE, to='glam.product')),
            ],
            options={
                'verbose_name': 'anomaly baseline dataset',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sticky', models.BooleanField(default=False, help_text='If multiple messages, keep this message at front/first')),
                ('header', models.TextField(help_text='Announcement Header')),
                ('message', models.TextField(help_text='Announcement')),
                ('image', models.ImageField(blank=True, help_text='Announcement Image.', null=True, storage=config.storage_backends.PublicStorage(), upload_to='announcements')),
                ('tags', models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unit_name', models.CharField(help_text='Administrative layer name.', max_length=256)),
                ('admin_unit_id', models.BigIntegerField(db_index=True, help_text='A unique character ID to identify Administrative Layer records.', null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('admin_layer', models.ForeignKey(help_text='layer that administrative unit belongs to', on_delete=django.db.models.deletion.CASCADE, to='glam.adminlayer')),
            ],
            options={
                'verbose_name': 'administrative unit',
            },
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='masks',
            field=models.ManyToManyField(help_text='Cropmasks that are available for the Administrative Layer. (for ZonalStats generation)', to='glam.CropMask'),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='source',
            field=models.ForeignKey(help_text='Administrative Layer source.', on_delete=django.db.models.deletion.PROTECT, to='glam.datasource'),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag'),
        ),
        migrations.AddField(
            model_name='admindataset',
            name='admin_layer',
            field=models.ForeignKey(help_text='Administrative Layer that the dataset belongs to.', on_delete=django.db.models.deletion.CASCADE, to='glam.adminlayer'),
        ),
        migrations.AddField(
            model_name='admindataset',
            name='product',
            field=models.ForeignKey(help_text='Product that the Administrative Layer dataset belongs to.Necessary for matching product resolution in ZonalStats calculation.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_datasets', to='glam.product'),
        ),
        migrations.AddIndex(
            model_name='zonalstats',
            index=models.Index(fields=['product_dataset', 'mask_dataset', 'admin_dataset', 'admin_unit_id', 'date'], name='zstats_idx'),
        ),
        migrations.AddIndex(
            model_name='zonalstats',
            index=models.Index(fields=['product_dataset', 'mask_dataset', 'admin_dataset', 'admin_unit_id'], name='zstats_idx_no_date'),
        ),
        migrations.AddIndex(
            model_name='adminunit',
            index=models.Index(fields=['admin_unit_name', 'admin_unit_id', 'admin_layer'], name='adminunit_name_id_layer_idx'),
        ),
    ]
