# Generated by Django 3.2.15 on 2022-10-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlayer',
            name='desc_en',
            field=models.TextField(help_text='Brief description of Adminsitrative Layer.', null=True),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='desc_es',
            field=models.TextField(help_text='Brief description of Adminsitrative Layer.', null=True),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='desc_pt',
            field=models.TextField(help_text='Brief description of Adminsitrative Layer.', null=True),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='display_name_en',
            field=models.CharField(help_text='Administrative Layer display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='display_name_es',
            field=models.CharField(help_text='Administrative Layer display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='adminlayer',
            name='display_name_pt',
            field=models.CharField(help_text='Administrative Layer display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='header_en',
            field=models.TextField(help_text='Announcement Header', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='header_es',
            field=models.TextField(help_text='Announcement Header', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='header_pt',
            field=models.TextField(help_text='Announcement Header', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_en',
            field=models.TextField(help_text='Announcement', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_es',
            field=models.TextField(help_text='Announcement', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_pt',
            field=models.TextField(help_text='Announcement', null=True),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='desc_en',
            field=models.TextField(help_text='Brief cropmask decription.', null=True),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='desc_es',
            field=models.TextField(help_text='Brief cropmask decription.', null=True),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='desc_pt',
            field=models.TextField(help_text='Brief cropmask decription.', null=True),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='display_name_en',
            field=models.CharField(help_text='Cropmask display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='display_name_es',
            field=models.CharField(help_text='Cropmask display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cropmask',
            name='display_name_pt',
            field=models.CharField(help_text='Cropmask display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='desc_en',
            field=models.TextField(help_text='Brief source description.', null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='desc_es',
            field=models.TextField(help_text='Brief source description.', null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='desc_pt',
            field=models.TextField(help_text='Brief source description.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_en',
            field=models.TextField(help_text='Description of product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_es',
            field=models.TextField(help_text='Description of product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_pt',
            field=models.TextField(help_text='Description of product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_name_en',
            field=models.CharField(help_text='Product display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_name_es',
            field=models.CharField(help_text='Product display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_name_pt',
            field=models.CharField(help_text='Product display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='desc_en',
            field=models.TextField(help_text='Description of variable measured by product.', null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='desc_es',
            field=models.TextField(help_text='Description of variable measured by product.', null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='desc_pt',
            field=models.TextField(help_text='Description of variable measured by product.', null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='display_name_en',
            field=models.CharField(help_text='Variable display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='display_name_es',
            field=models.CharField(help_text='Variable display name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='display_name_pt',
            field=models.CharField(help_text='Variable display name.', max_length=256, null=True),
        ),
    ]
