# Generated by Django 4.2.14 on 2024-12-10 20:53

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Announcement Image.', null=True, storage=config.storage.S3PrivateMediaStorage(), upload_to='announcements'),
        ),
        migrations.AlterField(
            model_name='anomalybaselineraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/home/ubuntu/glam-api/glam_api/local_files/baseline_datasets', recursive=True),
        ),
        migrations.AlterField(
            model_name='cropmaskraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/home/ubuntu/glam-api/glam_api/local_files/mask_datasets', recursive=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='logo',
            field=models.ImageField(blank=True, help_text='Source logo.', null=True, storage=config.storage.S3PrivateMediaStorage(), upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_object',
            field=models.FileField(blank=True, help_text='Document file.', storage=config.storage.S3PrivateMediaStorage(), upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='productraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to for local development.', match='.*\\.tif$', max_length=256, path='/home/ubuntu/glam-api/glam_api/local_files/product_datasets', recursive=True),
        ),
    ]
