# Generated by Django 3.2.15 on 2022-12-12 14:41

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropmask',
            name='vector_file',
        ),
        migrations.AddField(
            model_name='cropmask',
            name='source_file',
            field=models.FileField(blank=True, help_text='Original source file(s). Raster or Vector. (If Available)', null=True, storage=config.storage_backends.RasterStorage(), upload_to='masks'),
        ),
        migrations.AlterField(
            model_name='boundarylayer',
            name='original_data',
            field=models.FileField(blank=True, help_text='Original Boundary Layer raster or vector', null=True, storage=config.storage_backends.RasterStorage(), upload_to='boundary-layers'),
        ),
        migrations.AlterField(
            model_name='cropmask',
            name='raster_file',
            field=models.FileField(blank=True, help_text='Cloud Optimized Geotiff to be used for visualization in TMS.', null=True, storage=config.storage_backends.RasterStorage(), upload_to='masks'),
        ),
    ]
