# Generated by Django 4.2.17 on 2024-12-19 16:09

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0002_alter_announcement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productraster',
            name='file_object',
            field=models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage.RasterStorage(), upload_to='product-rasters'),
        ),
    ]
