# Generated by Django 3.2.15 on 2022-12-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0002_auto_20221212_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boundarylayer',
            old_name='original_data',
            new_name='source_data',
        ),
    ]
