# Generated by Django 4.2.17 on 2025-01-08 20:46

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0003_alter_productraster_file_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundarylayer',
            name='source_data',
            field=models.FileField(blank=True, help_text='Original Boundary Layer raster or vector', null=True, storage=config.storage.S3PrivateMediaStorage(), upload_to='boundary-layers'),
        ),
        migrations.AlterField(
            model_name='boundarylayer',
            name='vector_file',
            field=models.FileField(blank=True, help_text='Vector geometry file for visual representation in the GLAM application', null=True, storage=config.storage.S3PrivateMediaStorage(), upload_to='boundary-layers'),
        ),
    ]
