# Generated by Django 3.2.15 on 2023-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0003_cropmask_mask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmask',
            name='mask_type',
            field=models.CharField(choices=[('binary', 'Binary (Crop or No Crop)'), ('percent', 'Percent Crop')], default='binary', help_text='Type of values present in mask raster (binary or percent crop).', max_length=32),
        ),
        migrations.AlterField(
            model_name='cropmaskraster',
            name='mask_type',
            field=models.CharField(choices=[('binary', 'Binary (Crop or No Crop)'), ('percent', 'Percent Crop')], default='binary', help_text='Type of values present in mask raster (binary or percent crop). Used for zonal statistics calculations.', max_length=32),
        ),
    ]
