# Generated by Django 3.2.15 on 2022-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0003_rename_original_data_boundarylayer_source_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaryraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', path='/data/glam2/api/glam_api/local_files/boundary_rasters', recursive=True),
        ),
        migrations.AlterField(
            model_name='maskdataset',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', path='/data/glam2/api/glam_api/local_files/cropmask_rasters', recursive=True),
        ),
        migrations.AlterField(
            model_name='productdataset',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', path='/data/glam2/api/glam_api/local_files/product_rasters', recursive=True),
        ),
    ]
