# Generated by Django 3.2.15 on 2022-12-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0004_auto_20221212_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnomalyBaselineDataset',
            new_name='AnomalyBaselineRaster',
        ),
        migrations.RenameModel(
            old_name='MaskDataset',
            new_name='CropmaskRaster',
        ),
        migrations.RenameModel(
            old_name='ProductDataset',
            new_name='ProductRaster',
        ),
        migrations.RemoveIndex(
            model_name='zonalstats',
            name='zstats_idx',
        ),
        migrations.RemoveIndex(
            model_name='zonalstats',
            name='zstats_idx_no_date',
        ),
        migrations.RenameField(
            model_name='zonalstats',
            old_name='boundary_dataset',
            new_name='boundary_raster',
        ),
        migrations.RenameField(
            model_name='zonalstats',
            old_name='mask_dataset',
            new_name='cropmask_raster',
        ),
        migrations.RenameField(
            model_name='zonalstats',
            old_name='product_dataset',
            new_name='product_raster',
        ),
        migrations.AddIndex(
            model_name='zonalstats',
            index=models.Index(fields=['product_raster', 'cropmask_raster', 'boundary_raster', 'feature_id', 'date'], name='zstats_idx'),
        ),
        migrations.AddIndex(
            model_name='zonalstats',
            index=models.Index(fields=['product_raster', 'cropmask_raster', 'boundary_raster', 'feature_id'], name='zstats_idx_no_date'),
        ),
    ]
