# Generated by Django 3.2.15 on 2023-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0004_auto_20230104_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalybaselineraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/gpfs/data1/cmongp2/GLAM/glam-api/glam_api/local_files/baselines', recursive=True),
        ),
        migrations.AlterField(
            model_name='boundaryraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/gpfs/data1/cmongp2/GLAM/glam-api/glam_api/local_files/boundary_rasters', recursive=True),
        ),
        migrations.AlterField(
            model_name='cropmaskraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/gpfs/data1/cmongp2/GLAM/glam-api/glam_api/local_files/cropmask_rasters', recursive=True),
        ),
        migrations.AlterField(
            model_name='productraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/gpfs/data1/cmongp2/GLAM/glam-api/glam_api/local_files/product_rasters', recursive=True),
        ),
    ]
