# Generated by Django 3.2.15 on 2022-12-12 16:28

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0005_auto_20221212_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaryraster',
            name='file_object',
            field=models.FileField(blank=True, help_text='Stored dataset file. When dataset object is saved, the file_object is created using the local_path.', storage=config.storage_backends.RasterStorage(), upload_to='boundaries'),
        ),
    ]
