# Generated by Django 3.2.15 on 2023-01-10 15:31

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0005_auto_20230106_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropmask',
            old_name='raster_file',
            new_name='map_raster',
        ),
        migrations.AddField(
            model_name='cropmask',
            name='stats_raster',
            field=models.FileField(blank=True, help_text='Cloud Optimized Geotiff to be used for zonal statistics calculations.', null=True, storage=config.storage_backends.RasterStorage(), upload_to='cropmasks'),
        ),
    ]
