# Generated by Django 3.2.15 on 2022-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0007_auto_20221212_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmask',
            name='coverage',
            field=models.CharField(default='Global', help_text='Text representation of spatial coverage/extent of crop mask.', max_length=256),
        ),
    ]
