# Generated by Django 3.2.15 on 2023-01-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0007_alter_productraster_file_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmask',
            name='stats_mask_type',
            field=models.CharField(choices=[('binary', 'Binary (Crop or No Crop)'), ('percent', 'Percent Crop')], default='binary', help_text='Type of values present in mask raster for calculating zonal statistics (binary or percent crop).', max_length=32),
        ),
        migrations.AlterField(
            model_name='cropmask',
            name='mask_type',
            field=models.CharField(choices=[('binary', 'Binary (Crop or No Crop)'), ('percent', 'Percent Crop')], default='binary', help_text='Type of values present in mask raster for map visualization (binary or percent crop).', max_length=32),
        ),
    ]
