# Generated by Django 3.2.15 on 2022-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0008_cropmask_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmaskraster',
            name='mask_type',
            field=models.CharField(choices=[('binary', 'Binary (Crop or No Crop'), ('percent', 'Percent Crop')], default='binary', help_text='Type of values present in mask raster (binary or percent crop). Used for zonal statistics calculations.', max_length=32),
        ),
    ]
