# Generated by Django 3.2.15 on 2022-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0009_cropmaskraster_mask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productraster',
            name='local_path',
            field=models.FilePathField(help_text='Path to dataset on current machine. Used to upload dataset file_object.', match='.*\\.tif$', max_length=256, path='/data/glam2/api/glam_api/local_files/product_rasters', recursive=True),
        ),
    ]
