# Generated by Django 3.2.15 on 2023-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0011_zonalstats_unique_stats_record_null_cropmask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonalstats',
            name='max',
            field=models.FloatField(blank=True, help_text='Maximum value derived from zonal statistics calculatin.', null=True),
        ),
        migrations.AlterField(
            model_name='zonalstats',
            name='mean',
            field=models.FloatField(blank=True, help_text='Mean value derived from zonal statistics calculation.', null=True),
        ),
        migrations.AlterField(
            model_name='zonalstats',
            name='min',
            field=models.FloatField(blank=True, help_text='Minimum value derived from zonal statistics calculation.', null=True),
        ),
        migrations.AlterField(
            model_name='zonalstats',
            name='std',
            field=models.FloatField(blank=True, help_text='Standard deviation derived from zonal statistics calculation.', null=True),
        ),
    ]
