# Generated by Django 3.2.15 on 2023-03-28 18:40

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0012_auto_20230127_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name.', max_length=256)),
                ('document_id', models.SlugField(blank=True, help_text='A unique character ID to identify document.', max_length=256, unique=True)),
                ('desc', models.TextField(blank=True, help_text='Description of document.', null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('file_object', models.FileField(blank=True, help_text='Document file.', storage=config.storage_backends.PublicStorage(), upload_to='documents')),
                ('tags', models.ManyToManyField(blank=True, help_text='Optional tags to help searching and filtering.', to='glam.Tag')),
            ],
        ),
    ]
