# Generated by Django 3.2.15 on 2023-03-28 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glam', '0013_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 14, 55, 0, 924414), help_text='Date the document was created/modified.'),
            preserve_default=False,
        ),
    ]
